<?php
use ObjectivePHP\Application\Config\ApplicationName;
use ObjectivePHP\Application\View\Helper\Vars;
?>

<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="#"><?= Vars::$config->get(ApplicationName::class) ?></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="http://github.com/objective-php">Objective PHP on GitHub</a>
                </li>
            </ul>
        </div>
    </div>
</nav>